variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  FONTAWESOME_TOKEN: "$FONTAWESOME_TOKEN"

cache:
  paths:
    - node_modules/

stages:
  - install
  - lint
  - build
  # - test
  - upload

default:
  image: firexstuff/firex-alpine-build:mo

install:
  stage: install
  script:
    # - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
    # - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_TOKEN
    - npm ci

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

# replace jest mocking with vite mocking.
# test-unit:
#   stage: test
#   script:
#     - npm run test:unit

upload-pkg:
  stage: upload
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install --upgrade firexbuilder
    - cd dist
  script:
    - pip install keyrings.alt
    - python3 setup.py sdist
    - firex-build upload_pip
  only:
    - tags

deploy-public:
  stage: upload
  image: google/cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
    - gsutil -m rsync -r dist gs://www.firexstuff.com$DEPLOY_PATH
    # enable the public UI config
    - gsutil mv gs://www.firexstuff.com$DEPLOY_PATH/public-flame-ui-config.json gs://www.firexstuff.com$DEPLOY_PATH/flame-ui-config.json
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      variables:
        DEPLOY_PATH: /flame/$CI_JOB_ID
    - if: $CI_COMMIT_TAG
      variables:
        DEPLOY_PATH: '/flame'

