
steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com:FireXStuff/firex-flame-ui.git']
  dir: '$BUILD_ID'
- name: gcr.io/$PROJECT_ID/firex-alpine-build
  args: ['sh', '-c', 'npm ci && npm run build && cd dist/ && python3 setup.py sdist && twine upload dist/*']
  dir: '$BUILD_ID/firex-flame-ui'
  secretEnv: ['TWINE_PASSWORD']

secrets:
- kmsKeyName: projects/firex-kit-documentation/locations/global/keyRings/secrets/cryptoKeys/TWINE_PASSWORD
  secretEnv:
    TWINE_PASSWORD: 'CiQAI+bsJfbKBVxA+tOJAGnHIJRG0zFyUbzjvBx3S0BSF0T3UdUSOgDnI0hgPR5iY1f1pYZJUaPASEjviB8mzBIlAEI0LSMy+r9FUOIKIPDTO4lQN8BWsq3ksNAhe8f5aKA='