
steps:
- name: gcr.io/firex-kit-documentation/firex-alpine-build@sha256:68b256cd111a957b7f4832a9c9000eebc575e6b9084f3518fc5b7b82241ac620
  args: ['sh', '-c', 'sudo git clone https://github.com/FireXStuff/firex-flame-ui.git && cd firex-flame-ui && sudo npm ci && sudo npm run build && cd dist/ && sudo python3 setup.py sdist && ! git describe --tags --exact-match  || twine upload --username firexdev dist/*']
  dir: '$BUILD_ID'
  secretEnv: ['TWINE_PASSWORD']

secrets:
- kmsKeyName: projects/firex-kit-documentation/locations/global/keyRings/secrets/cryptoKeys/TWINE_PASSWORD
  secretEnv:
    TWINE_PASSWORD: 'CiQAI+bsJWZL0S/bFCabcznzcBMmAhWgs5e2gXI2Yi9nyfhWxm4SOQDnI0hgaoMJolUfZg9GZKnq2RA/Im2ZhFBIqcXkNpr/dEBuFBLIJFWjnXCHTR4jlQ+8s8GwECRbQw=='
